---
  - name: Installing sonarqube and it's dependencies
    hosts: all
    become: true
    remote_user: ubuntu
    tasks:
    - name: Run a remote shell script
      ansible.builtin.shell: sonar.sh
    # roles:
    #   - sonarqube
