---
    - name: Ensure psycopg2 library is installed
      become: yes
      ansible.builtin.package:
       name: "{{ 'python3-psycopg2' if ansible_os_family == 'Debian' else 'python3-psycopg2' }}"
       state: present

    - name: Install PostgreSQL
      become: yes
      ansible.builtin.package:
       name: "{{ postgresql_pkg_name }}"
       state: present

    - name: Initialize PostgreSQL database (CentOS only)
      become: yes
      ansible.builtin.command: /usr/bin/postgresql-setup initdb
      when: ansible_os_family == "RedHat"
    
    - name: Start and enable PostgreSQL
      become: yes
      ansible.builtin.service:
       name: postgresql
       state: started
       enabled: true

#   - name: Configure PostgreSQL to allow SonarQube user access
#     become_user: postgres
#     ansible.builtin.postgresql_user:
#      name: "{{ postgresql_user }}"
#      password: "{{ postgresql_password }}"
#      role_attr_flags: "CREATEDB"
#       host: localhost

