---
    - name: Install dependencies
      ansible.builtin.package:
       name: "{{ item }}"
       state: present
      loop:
       - unzip
       - wget
       - openjdk-11-jdk  # for Debian
#      - java-11-openjdk # for RedHat

    - name: Download SonarQube
      ansible.builtin.get_url:
       url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
       dest: "/tmp/sonarqube-{{ sonarqube_version }}.zip"

    - name: Extract SonarQube
      ansible.builtin.unarchive:
       src: "/tmp/sonarqube-{{ sonarqube_version }}.zip"
       dest: "{{ sonarqube_install_dir }}"
       remote_src: yes
      # extra_opts: [--strip-components=1]
    
    - name: create directory
      file:
       path: "{{ sonarqube_install_dir }}"
       state: directory

    - name: Set up SonarQube user
      ansible.builtin.user:
       name: "{{ sonarqube_user }}"
       home: "{{ sonarqube_install_dir }}"
       shell: /bin/false

